App = require 'app'

module.exports = App.Cube = DS.Model.extend
    cube_id: DS.attr 'string'
    camera: DS.attr 'string'
    year: DS.attr 'date'
    cube_number: DS.attr 'number'
    image_type: DS.attr 'string'
    gradient: DS.attr 'number'
    order: DS.belongsTo("App.Order")
    employee: DS.attr 'number'
    comment: DS.attr 'string'
    retake: DS.attr 'boolean'
    retake_id: DS.attr 'string'
    author: DS.attr 'string'
    created: DS.attr 'date'
    meters: DS.attr 'number'
    m1_hole: DS.attr 'string'
    m1_project: DS.attr 'string'
    m1_from: DS.attr 'number'
    m1_to: DS.attr 'number'
    m1_unit: DS.attr 'string'
    m2_hole: DS.attr 'string'
    m2_project: DS.attr 'string'
    m2_from: DS.attr 'number'
    m2_to: DS.attr 'number'
    m2_unit: DS.attr 'string' 
    #meters: DS.hasMany 'App.Meter'  #DS.belongsTo 'App.Meter' # DS.attr 'string' 
    
